baseurl = "https://abskmj.github.io/notes/"
languageCode = "en-us"
Title = "console.log('Hello World!');"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; 2017 abskmj"
theme = "hugo_theme_pickles"

# Google Analytics API key.
# googleAnalytics = ""

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  # twitter = "Your Twitter username"
  # facebook = "Your Facebook username"
  # instagram = "Your Instagram username"
  # googleplus = "Your Google+ account URL" # https://plus.google.com/u/0/xxxxxx
  github = "abskmj"
  gitlab = "abskmj"
  npm = "~abskmj"
  # codepen = "Your CodePen username"
  # dribbble = "Your Dribbble username"
  # fivehundredpx = "Your 500px username" # 500px
  # flickr = "Your Flickr username"
  # pinterest = "Your Pinterest username"
  # tumblr = "Your Tumblr username"
  # vimeo = "Your Vimeo username"
  # youtube = "Your YouTube username"
  # linkedin = "Your LinkedIn username"
  # Disqus shortname
  # disqus = ""
  # Google Analytics API key.
  ga_api_key = "UA-82450306-3"
  author = "abskmj"
  # authorwebsite = "example.com"
  # avatar = "/path/to/avatar"
  contact = "mailto:abskmj@gmail.com"
  bio = "Designing and developing web based applications since 2012. Keen on exploring and working on new technologies to implement innovative and cutting-edge solutions."
  # Short subtitle/tagline. This is displayed in the header.
  # subtitle = "Short subtitle"
  # Logo image. This is displayed ogp image.
  # logo = "/path/to/logo"
  # favicon = "/path/to/favicon"