name: Deploy to GH Pages
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install hugo
      run: |
       sudo snap install hugo
       hugo version
    - name: Install hugo theme
      run: |
        git clone https://github.com/panr/hugo-theme-terminal.git themes/terminal
    - name: Build
      run: hugo
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
